version: '3'

services:
  web:
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
